Implemented Config File
lucasadamski/SpanishWords pull request #3
Opened 2024-02-19 14:44 UTC by lucasadamski

Extracted Correct Number For Learning A Word to Config File (appsettings.json)

My config file:

{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*",
  "ConnectionStrings": {
    "Default": "Data Source=COMPUTER\\MSSQLSERVER01;Database=SpanishWords;Integrated Security=True;Connect Timeout=60;Encrypt=False;Trust Server Certificate=False;Application Intent=ReadWrite;Multi Subnet Failover=False",
    "WordsContextConnection": "Server=(localdb)\\mssqllocaldb;Database=SpanishWords.Web;Trusted_Connection=True;MultipleActiveResultSets=true"
  },
  "NumberForCorrectsAnswersToLearn":  3
}

2024-02-19 15:25 UTC, klaudiaRajs requested changes

2024-02-19 15:25 UTC, klaudiaRajs commented on SpanishWords.Web/Helpers/SettingsHelper.cs
> +            if (config == null) return 0;
Tu zamiast zera możesz zwrócić CORRECT_NUMBER_FOR_LEARNING. A dodatkowo, zaloguj do pliku, że nie masz w konfiguracji odpowiednich parametrów.

2024-02-20 08:19 UTC, lucasadamski commented on SpanishWords.Web/Helpers/SettingsHelper.cs
> +            if (config == null) return 0;
Pierwszą część zrobiłem, jednak nie jestem w stanie zrobić Dependency Injection do statycznej klasy..

2024-03-13 12:36 UTC, merged

2024-05-29 09:52 UTC, klaudiaRajs commented on SpanishWords.Web/Helpers/SettingsHelper.cs
> +            if (config == null) return 0;
A czemu chcesz robić dependency injection 🤔 ?